export const ProjectData = [
  {
    id: 1,
    src: "../../public/project1.svg",
    title: "Project 1",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "WallBox",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Trading",
  },
  {
    id: 2,
    src: "../../public/project2.svg",
    title: "Project 2",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Trading",
  },
  {
    id: 3,
    src: "../../public/project3.svg",
    title: "Project 3",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Trading",
  },
  {
    id: 4,
    src: "../../public/project4.svg",
    title: "Project 4",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Switchgear",
  },
  {
    id: 5,
    src: "../../public/project5.svg",
    title: "Project 5",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Switchgear",
  },
  {
    id: 6,
    src: "../../public/project6.svg",
    title: "Project 6",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Building Automation",
  },
  {
    id: 7,
    src: "../../public/project7.svg",
    title: "Project 7",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Energy",
  },
  {
    id: 8,
    src: "../../public/project8.svg",
    title: "Project 8",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Energy",
  },
  {
    id: 9,
    src: "../../public/project9.svg",
    title: "Project 9",
    description:
      "Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum. Hac vitae sem class fames vehicula nascetur nam tellus a condimentum inceptos mus rhoncus et accumsan fringilla vehicula nascetur amet fermentum rutrum.",
    Client: "Schnider",
    Consultant: "John Doe",
    MainContractor: "Wood, Paper",
    MepContractor: "xtemos.com/wood",
    SystemProvider: "xxxxx",
    ProjectStatus: "Complete",
    category: "Energy",
  },
];
